name: Nadzu Local
values:
  - key: base_url
    value: 'http://127.0.0.1:8080'
  - key: base_url_tls
    value: 'https://nadzu.localhost'
  - key: api_key
    value: ''
  - key: video_url
    value: ''
color: 120
