name: nadzu-dev

services:
  app:
    # run `make bd' to build the local image for development.image name 'nadzu:local`.
    # For production deployments, use the published image `ghcr.io/nxdun/nadzu:latest` or an appropriate tagged release.
    image: nadzu:local
    environment:
      APP_HOST: "0.0.0.0"
      APP_PORT: "8080"
      APP_ENV: "development"
      APP_NAME: "nadzu"
      DOWNLOAD_DIR: "/app/downloads"
      RUST_LOG: "debug"
      ALLOWED_ORIGINS: "https://nadzu.localhost, http://localhost:8080"
      CAPTCHA_SECRET_KEY: ${CAPTCHA_SECRET_KEY}
      MASTER_API_KEY: "${MASTER_API_KEY}"

    volumes:
      - ./downloads:/app/downloads

  caddy:
    image: caddy:2-alpine
    container_name: nadzu-caddy-dev
    ports:
      - "80:80"
      - "443:443"
      - "2026:2026"
      - "8080:8080"
    volumes:
      - ./Caddyfile.local:/etc/caddy/Caddyfile:ro
      - ./infra/common/browse.html:/etc/caddy/browse.html:ro
      - ./downloads:/var/www/downloads:ro
    depends_on:
      - app 

  prometheus:
    image: prom/prometheus:latest
    container_name: nadzu-prometheus
    volumes:
      - ./infra/common/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: nadzu-grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_ROOT_URL=https://nadzu.localhost/nadun/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    ports:
      - "3000:3000"
    volumes:
      - ./infra/common/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus

volumes:
  app-target:
  app-cargo:
