FROM rust:slim-bookworm

RUN apt-get update && apt-get install -y \
    pkg-config libssl-dev ffmpeg python3 python3-pip python3-venv curl \
    && rm -rf /var/lib/apt/lists/*

# Set up virtual environment and install yt-dlp
RUN python3 -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"
RUN pip install --no-cache-dir yt-dlp

WORKDIR /app

ENV HOME=/root
ENV CARGO_HOME=/usr/local/cargo
ENV CARGO_TARGET_DIR=/app/target_docker

RUN cargo install cargo-watch

CMD ["cargo", "watch", "-x", "run"]