services:
  app:
    image: ${IMAGE:-nadzu}:${TAG:-local}
    # image: ${IMAGE:-ghcr.io/nxdun/nadzu}:${TAG:-latest}
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    #   args:
    #     MODE: ${MODE:-debug}
    #     BIN: ${BIN:-nadzu}
    environment:
      RUST_LOG: info
      APP_HOST: 0.0.0.0
      APP_ENV: development
      CAPTCHA_SECRET_KEY: ${CAPTCHA_SECRET_KEY}
      YTDLP_COOKIES_FILE: /run/secrets/ytdlp_cookies.txt
    volumes:
      - ${YTDLP_COOKIES_FILE}:/run/secrets/ytdlp_cookies.txt:ro
    ports:
      - "8080:8080"
