module "digitalocean_stack" {
  source = "../../components"
  APP_ENV                   = var.APP_ENV
  ALLOWED_ORIGINS           = var.ALLOWED_ORIGINS
  DOWNLOAD_DIR              = var.DOWNLOAD_DIR
  MAX_CONCURRENT_DOWNLOADS  = var.MAX_CONCURRENT_DOWNLOADS
  RUST_LOG                  = var.RUST_LOG
  APP_HOST                  = var.APP_HOST
  DO_TOKEN                  = var.DO_TOKEN
  PROJECT_NAME              = var.PROJECT_NAME
  ENVIRONMENT               = var.ENVIRONMENT
  REGION                    = var.REGION
  DROPLET_NAME              = var.DROPLET_NAME
  DROPLET_SIZE              = var.DROPLET_SIZE
  DROPLET_IMAGE             = var.DROPLET_IMAGE
  VOLUME_NAME               = var.VOLUME_NAME
  VOLUME_SIZE_GIB           = var.VOLUME_SIZE_GIB
  GHCR_IMAGE                = var.GHCR_IMAGE
  GHCR_PAT                  = var.GHCR_PAT
  GITHUB_USERNAME           = var.GITHUB_USERNAME
  APP_PORT                  = var.APP_PORT
  HOST_PORT                 = var.HOST_PORT
  DOWNLOADS_MOUNT_PATH      = var.DOWNLOADS_MOUNT_PATH
  DOCKER_CONTAINER_NAME     = var.DOCKER_CONTAINER_NAME
  DOCKER_RESTART_POLICY     = var.DOCKER_RESTART_POLICY
  CAPTCHA_SECRET_KEY        = var.CAPTCHA_SECRET_KEY
  YTDLP_PRESIGNED_URL       = var.YTDLP_PRESIGNED_URL
}
